[package]
name = "aoc-2022"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "03"
path = "src/03.rs"

[[bin]]
name = "04"
path = "src/04.rs"

[[bin]]
name = "06"
path = "src/06.rs"

[[bin]]
name = "07"
path = "src/07.rs"

[[bin]]
name = "09"
path = "src/09.rs"
